name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    
    # Activate cache
    - name: Start DXSDK Cache
      id:   dxcache
      uses: actions/cache@v1
      with:
       path: DXSDK
       key:  dxsdk-includes
      
    # Download DXSDK if needed, otherwise use cache
    # Only extract files that are required
    - name:  Download DXSDK if needed
      if:    steps.dxcache.outputs.cache-hit != 'true'
      run:   |
         curl -L https://download.microsoft.com/download/a/e/7/ae743f1f-632b-4809-87a9-aa1bb3458e31/DXSDK_Jun10.exe -o _DX2010_.exe
         7z x _DX2010_.exe DXSDK/Include
         7z x _DX2010_.exe DXSDK/Lib/x86
         rm -fR _DX*_ _DX*_.exe
      shell: bash
      
    - name: MSBuild
      working-directory: base
      run: msbuild cinnamon.vcxproj /p:Configuration=Release /v:m
      env:
        DXSDK_DIR: ${{ github.workspace }}\DXSDK\
    - name: SHA1
      working-directory: build/Release
      run: sha1sum base.dll > base.dll.sha1
      
    - uses: actions/upload-artifact@v1
      with:
        name: Release
        path: build/Release
